/** Simplified Chinese text for backend-provided settings enum labels and descriptions. */
export const ZH_SCHEMA_OPTION_TEXT: Readonly<Record<string, string>> = {
	Stable: "稳定版",
	Canary: "预览版",
	Mechanical: "规则检测",
	"Short (5m)": "短期（5 分钟）",
	"Long (1h)": "长期（1 小时）",
	"Provider default — Anthropic uses 5m entries kept warm by idle keep-alive refreshes; PI_CACHE_RETENTION still applies":
		"使用提供商默认值；Anthropic 使用 5 分钟缓存，空闲时续期；仍遵循 PI_CACHE_RETENTION。",
	"Cheapest cache writes; Anthropic keeps the entry warm with bounded keep-alive refreshes while idle":
		"缓存写入成本最低；Anthropic 在空闲时进行有限次数的续期。",
	"1h TTL where the provider supports it; pricier writes, no keep-alive refresh requests":
		"支持时保留 1 小时；写入费用更高，不发送缓存续期请求。",
	"Disable prompt caching and cache-affinity routing": "关闭提示词缓存及缓存亲和路由。",
	Off: "关闭",
	"Do not prevent any sleep": "不阻止任何休眠",
	"Prevent Idle Sleep": "阻止空闲休眠",
	"Keep the system awake while a session is open (caffeinate -i)": "会话打开时保持系统唤醒（caffeinate -i）",
	"Prevent Display Sleep": "阻止显示器休眠",
	"Also keep the display from idle-sleeping (caffeinate -i -d)": "同时阻止显示器空闲休眠（caffeinate -i -d）",
	"Prevent System Sleep": "阻止系统休眠",
	"Also block all system sleep on AC and declare the user active (caffeinate -i -d -s -u)":
		"同时在接通电源时阻止所有系统休眠，并声明用户处于活动状态（caffeinate -i -d -s -u）",
	off: "关闭",
	"0 turns": "0 轮",
	"Allow every concern/blocker to interrupt.": "允许任何疑虑或阻碍因素中断。",
	"1 turn": "1 轮",
	"2 turns": "2 轮",
	"3 turns": "3 轮",
	"Default.": "默认。",
	"4 turns": "4 轮",
	"5 turns": "5 轮",
	Global: "全局",
	"Save role models in the active profile config (current behavior)":
		"将角色模型保存在当前配置文件的配置中（当前行为）",
	"Per-project": "按项目",
	"Save project role models in .omp/config.yml; missing project roles use global defaults":
		"将项目角色模型保存在 .omp/config.yml 中；缺失的项目角色使用全局默认值",
	Unicode: "Unicode",
	"Standard symbols (default)": "标准符号（默认）",
	"Nerd Font": "Nerd Font",
	"Requires Nerd Font": "需要 Nerd Font",
	ASCII: "ASCII",
	"Maximum compatibility": "最高兼容性",
	Default: "默认",
	"Model, path, git, context, tokens, cost": "模型、路径、git、上下文、token、成本",
	Minimal: "极简",
	"Path and git only": "仅路径和 git",
	Compact: "紧凑",
	"Model, git, cost, context": "模型、git、成本、上下文",
	Full: "完整",
	"All segments including time": "所有分段，包括时间",
	Nerd: "Nerd",
	"Maximum info with Nerd Font icons": "使用 Nerd Font 图标显示最多信息",
	"No special characters": "无特殊字符",
	Custom: "自定义",
	"User-defined segments": "用户定义的分段",
	Powerline: "Powerline",
	"Solid arrows (Nerd Font)": "实心箭头（Nerd Font）",
	"Thin chevron": "细尖括号",
	"Thin arrows (Nerd Font)": "细箭头（Nerd Font）",
	Slash: "斜杠",
	"Forward slashes": "正斜杠",
	Pipe: "竖线",
	"Vertical pipes": "垂直竖线",
	Block: "方块",
	"Solid blocks": "实心方块",
	None: "无",
	"Space only": "仅空格",
	"Greater-than signs": "大于号",
	"1 KB": "1 KB",
	"~250 tokens": "约 250 token",
	"2.5 KB": "2.5 KB",
	"~625 tokens": "约 625 token",
	"5 KB": "5 KB",
	"~1.25K tokens": "约 1.25K token",
	"10 KB": "10 KB",
	"~2.5K tokens": "约 2.5K token",
	"20 KB": "20 KB",
	"~5K tokens": "约 5K token",
	"30 KB": "30 KB",
	"~7.5K tokens": "约 7.5K token",
	"50 KB": "50 KB",
	"Default; ~12.5K tokens": "默认；约 12.5K token",
	"75 KB": "75 KB",
	"~19K tokens": "约 19K token",
	"100 KB": "100 KB",
	"~25K tokens": "约 25K token",
	"200 KB": "200 KB",
	"~50K tokens": "约 50K token",
	"500 KB": "500 KB",
	"~125K tokens": "约 125K token",
	"1 MB": "1 MB",
	"~250K tokens": "约 250K token",
	"Default; ~5K tokens": "默认；约 5K token",
	"~12.5K tokens": "约 12.5K token",
	"0 KB": "0 KB",
	"Disabled; tail-only truncation": "已禁用；仅从尾部截断",
	"No per-line cap": "无每行上限",
	Tight: "紧密",
	Loose: "宽松",
	"50 lines": "50 行",
	"100 lines": "100 行",
	"~500 tokens": "约 500 token",
	"250 lines": "250 行",
	"500 lines": "500 行",
	"Default; ~2.5K tokens": "默认；约 2.5K token",
	"1000 lines": "1000 行",
	"2000 lines": "2000 行",
	"~10K tokens": "约 10K token",
	"5000 lines": "5000 行",
	auto: "自动",
	always: "始终",
	Classic: "经典",
	"Soft cosine wave sweeping across the text": "柔和的余弦波扫过文本",
	"KITT Scanner": "KITT 扫描器",
	"Knight Rider 1982 red light bouncing left-right": "《Knight Rider》1982 年版红灯左右往返",
	Disabled: "已禁用",
	"No animation; static muted text": "无动画；静态弱化文本",
	"Auto-detect per prompt": "按提示词自动检测",
	min: "最低",
	"Very brief reasoning (~1k tokens)": "极简推理（约 1k token）",
	low: "低",
	"Light reasoning (~2k tokens)": "轻度推理（约 2k token）",
	medium: "中",
	"Moderate reasoning (~8k tokens)": "中度推理（约 8k token）",
	high: "高",
	"Deep reasoning (~16k tokens)": "深度推理（约 16k token）",
	xhigh: "极高",
	"Extended reasoning (~32k tokens)": "扩展推理（约 32k token）",
	max: "最高",
	"Maximum reasoning the model supports": "模型支持的最大推理量",
	Auto: "自动",
	"Inline descriptors for Gemini models; keep them in tool schemas otherwise":
		"对 Gemini 模型内联描述符；其他情况下保留在工具架构中",
	On: "开启",
	"Always inline descriptors in the system prompt": "始终在系统提示词中内联描述符",
	"Keep descriptors in provider tool schemas only": "仅将描述符保留在提供商工具架构中",
	"Terse, evidence-first engineer; dense, action-oriented replies":
		"简练、证据优先的工程师；回复信息密集且以行动为导向",
	Friendly: "友好",
	"Warm, encouraging collaborator focused on momentum and morale": "热情鼓励的协作者，注重推进节奏与士气",
	Pragmatic: "务实",
	"Direct, efficient engineer focused on clarity and rigor": "直接高效的工程师，注重清晰与严谨",
	"Omit the personality block entirely": "完全省略个性设定块",
	"Use provider default": "使用提供商默认值",
	Deterministic: "确定性",
	Focused: "专注",
	Balanced: "均衡",
	Creative: "创意",
	"Maximum variety": "最大多样性",
	"Very focused": "高度聚焦",
	Broad: "宽泛",
	"No nucleus filtering": "不进行核采样过滤",
	"Greedy top token": "贪心选择最高概率 token",
	"Very permissive": "非常宽松",
	Strict: "严格",
	"No penalty": "无惩罚",
	"Mild novelty": "轻度鼓励新颖性",
	"Encourage novelty": "鼓励新颖性",
	"Strong novelty": "强力鼓励新颖性",
	"Allow repetition": "允许重复",
	"Mild penalty": "轻度惩罚",
	"Strong penalty": "强惩罚",
	Low: "低",
	"Prefer concise responses": "倾向简洁回复",
	Medium: "中",
	"Balance brevity and detail (default)": "平衡简洁与细节（默认）",
	High: "高",
	"Prefer detailed responses": "倾向详细回复",
	"Omit service_tier (standard processing)": "省略 service_tier（标准处理）",
	"Provider default tier selection": "提供商默认层级选择",
	"Standard priority processing": "标准优先级处理",
	Flex: "Flex",
	"Lower cost, higher latency when available": "可用时成本更低、延迟更高",
	Scale: "Scale",
	"Scale Tier credits when available": "可用时使用 Scale Tier 额度",
	Priority: "优先",
	"Faster, higher cost (premium request)": "速度更快、成本更高（高级请求）",
	"Standard processing": "标准处理",
	'Fast mode (`speed: "fast"`) on supported direct Claude models; ignored on Bedrock/Vertex':
		'在受支持的直连 Claude 模型上使用快速模式（`speed: "fast"`）；在 Bedrock/Vertex 上忽略',
	"Lower cost, higher latency (Gemini API + Vertex)": "成本更低、延迟更高（Gemini API + Vertex）",
	"Faster, higher reliability (Gemini API + Vertex)": "速度更快、可靠性更高（Gemini API + Vertex）",
	Inherit: "继承",
	"Match the main agent's live per-family tiers": "匹配主代理当前按模型系列设置的层级",
	"Provider default tier selection (OpenAI family)": "提供商默认层级选择（OpenAI 系列）",
	"Standard priority processing (OpenAI family)": "标准优先级处理（OpenAI 系列）",
	"Flexible capacity tier (OpenAI/Google families)": "弹性容量层级（OpenAI/Google 系列）",
	"Scale Tier credits (OpenAI family)": "Scale Tier 额度（OpenAI 系列）",
	"Priority on every supported family of the spawned model": "对生成模型支持的每个系列使用优先处理",
	"1 retry": "重试 1 次",
	"2 retries": "重试 2 次",
	"3 retries": "重试 3 次",
	"5 retries": "重试 5 次",
	"10 retries": "重试 10 次",
	"Act only when nearly exhausted": "仅在即将耗尽时操作",
	"Balanced safety margin": "均衡的安全余量",
	Conservative: "保守",
	"Early protection": "提前保护",
	"Very conservative": "非常保守",
	"Confirm interactively": "交互式确认",
	"Keep interactive sessions on the primary until confirmed; background agents auto-fallback":
		"确认前，交互式会话继续使用主模型；后台代理自动回退",
	"Auto-fallback": "自动回退",
	"Always select the next eligible configured fallback": "始终选择下一个符合条件且已配置的回退模型",
	"Fail closed": "失败时拒绝",
	"Do not spend reserve quota or select a fallback": "不使用预留配额，也不选择回退模型",
	"Cooldown expiry": "冷却期结束",
	"Return to the primary model after its suppression window ends": "主模型的抑制期结束后切回该模型",
	Never: "从不",
	"Stay on the fallback model until manually changed": "保持使用回退模型，直到手动更改",
	all: "全部",
	"one-at-a-time": "逐个",
	immediate: "立即",
	wait: "等待",
	Prompt: "提示词",
	"Re-submit the prompt as a follow-up message (current behavior)": "将提示词作为后续消息重新提交（当前行为）",
	"Compact the session context, then re-submit the prompt": "压缩会话上下文，然后重新提交提示词",
	Reset: "重置",
	"Start a new session, then re-submit the prompt": "启动新会话，然后重新提交提示词",
	branch: "分支",
	tree: "树",
	none: "无",
	default: "默认",
	"no-tools": "无工具",
	"user-only": "仅用户",
	"labeled-only": "仅带标签",
	"3 items": "3 项",
	"5 items": "5 项",
	"7 items": "7 项",
	"10 items": "10 项",
	"15 items": "15 项",
	"20 items": "20 项",
	"Don't check for plugin updates": "不检查插件更新",
	Notify: "通知",
	"Check on startup and notify when updates are available": "启动时检查，有可用更新时通知",
	"Check on startup and auto-install updates": "启动时检查并自动安装更新",
	Summary: "摘要",
	"Show release and change counts with a /changelog hint": "显示版本发布数和变更数，并提示使用 /changelog",
	Expanded: "展开",
	"Show the recent release notes in full": "完整显示近期发行说明",
	Hidden: "隐藏",
	"Do not show release notes on startup": "启动时不显示发行说明",
	on: "开启",
	"15 seconds": "15 秒",
	"30 seconds": "30 秒",
	"60 seconds": "60 秒",
	"120 seconds": "120 秒",
	"1 minute": "1 分钟",
	"2 minutes": "2 分钟",
	"4 minutes": "4 分钟",
	"5 minutes": "5 分钟",
	"10 minutes": "10 分钟",
	"Encrypted Blob": "加密数据块",
	"Upload to the share server (no GitHub account needed; avoids gist API rate limits)":
		"上传到共享服务器（无需 GitHub 账户；可避开 gist API 速率限制）",
	"GitHub Gist": "GitHub Gist",
	"Push to a secret gist (needs authenticated gh), falling back to the share server":
		"推送到私密 gist（需要已认证的 gh），失败时回退到共享服务器",
	"Fast (Whisper base)": "快速（Whisper base）",
	"Whisper base, multilingual. Smallest + fastest; lowest accuracy. Best for low-resource machines.":
		"Whisper base，多语言。体积最小、速度最快；准确率最低。最适合低配置设备。",
	"Balanced (Whisper small)": "均衡（Whisper small）",
	"Whisper small, multilingual. More accurate than Fast, still light on CPU/RAM.":
		"Whisper small，多语言。比“快速”更准确，对 CPU/RAM 的占用仍较低。",
	"Turbo (Whisper large-v3)": "极速（Whisper large-v3）",
	"Whisper large-v3-turbo, 99 languages. Widest language coverage; large download, slower.":
		"Whisper large-v3-turbo，支持 99 种语言。语言覆盖最广；下载体积大，速度较慢。",
	"Parakeet TDT v3 (SoTA)": "Parakeet TDT v3（SoTA）",
	"NVIDIA Parakeet TDT 0.6B v3, 25 languages. Open ASR Leaderboard leader — best accuracy and far fastest decoding. Default.":
		"NVIDIA Parakeet TDT 0.6B v3，支持 25 种语言。Open ASR Leaderboard 榜首——准确率最高，解码速度遥遥领先。默认选项。",
	"Never automatically submit; insert dictation and remain in editor.": "从不自动提交；插入听写内容并停留在编辑器中。",
	Release: "松开时",
	"Submit on release if the utterance has 2+ words to avoid accidental sends.":
		"松开时，若话语包含至少 2 个单词则提交，以避免误发送。",
	"Release with complete sentence": "完整句子松开时",
	"Submit on release if the utterance ends with sentence-terminal punctuation (. ? ! etc.).":
		"松开时，若话语以句末标点（. ? ! 等）结尾则提交。",
	"When I Say Submit": "当我说 Submit 时",
	"Submit if the utterance ends with a word containing 'submit' (strips that word before submitting).":
		"若话语末尾单词包含“submit”，则提交（提交前移除该单词）。",
	"Context-full": "上下文已满",
	"Summarize in-place and keep the current session": "原地总结并保留当前会话",
	Handoff: "交接",
	"Generate handoff and continue in a new session": "生成交接内容并在新会话中继续",
	Shake: "精简",
	"Drop heavy content (tool results + large blocks) in place; recover via artifact":
		"原地移除大量内容（工具结果和大型内容块）；可通过 artifact 恢复",
	Snapcompact: "Snapcompact",
	"Archive history onto dense bitmap images the model reads back; no LLM call":
		"将历史记录归档为可供模型读回的高密度位图图像；无需调用 LLM",
	"OpenAI server compaction": "OpenAI 服务端压缩",
	"Use provider-native OpenAI-compatible server compaction when the active route supports it":
		"当前路由支持时，使用提供商原生的 OpenAI 兼容服务端压缩",
	"Archive history onto dense bitmap images the active vision model reads back; no LLM call":
		"将历史记录归档为当前视觉模型可读回的高密度位图；无需调用 LLM",
	"Generate a handoff document and continue from it as the compaction summary":
		"生成交接文档，并将其作为压缩摘要继续当前会话",
	"Soft compaction": "软压缩",
	"Summarize in place with a compaction model without using server compaction":
		"使用压缩模型原地总结，不调用服务端压缩",
	"Drop recoverable heavy content in place without an LLM call": "原地移除可恢复的大块内容；无需调用 LLM",
	"Disable automatic context maintenance (same behavior as Auto-compact off)":
		"禁用自动上下文维护（与关闭 Auto-compact 的行为相同）",
	"Legacy reserve-based threshold": "旧版基于预留量的阈值",
	"Extremely early maintenance": "极早维护",
	"Very early maintenance": "很早维护",
	"Early maintenance": "提前维护",
	"Moderately early maintenance": "适度提前维护",
	"Halfway point": "中点",
	"Moderate context usage": "适度使用上下文",
	"Slightly aggressive": "略激进",
	"Typical threshold": "典型阈值",
	"Aggressive context usage": "激进使用上下文",
	"Very aggressive": "非常激进",
	"Near context limit": "接近上下文上限",
	"Use percentage-based threshold": "使用基于百分比的阈值",
	"25K tokens": "25K token",
	"Quarter of a 200K window": "200K 窗口的四分之一",
	"50K tokens": "50K token",
	"Half of a 200K window": "200K 窗口的一半",
	"100K tokens": "100K token",
	"150K tokens": "150K token",
	"Three-quarters of a 200K window": "200K 窗口的四分之三",
	"200K tokens": "200K token",
	"Full standard context window": "完整的标准上下文窗口",
	"300K tokens": "300K token",
	"Large context window": "大上下文窗口",
	"500K tokens": "500K token",
	"Very large context window": "超大上下文窗口",
	"400K tokens": "400K token",
	"600K tokens": "600K token",
	"700K tokens": "700K token",
	"800K tokens": "800K token",
	"900K tokens": "900K token",
	"30 minutes": "30 分钟",
	"1 hour": "1 小时",
	"Keep the system prompt as text.": "将系统提示词保留为文本。",
	"AGENTS.md": "AGENTS.md",
	"Only move loaded context-file instructions to images, when that saves tokens.":
		"仅当能节省 token 时，才将已加载的上下文文件指令转为图像。",
	All: "全部",
	"Move the full system prompt to images, when that saves tokens.": "当能节省 token 时，将完整系统提示词转为图像。",
	"Use native tool calls unless the model is known not to support them.": "除非已知模型不支持，否则使用原生工具调用。",
	Native: "原生",
	"Use provider-native tool calls.": "使用提供商原生工具调用。",
	GLM: "GLM",
	"Use GLM-style in-band tool calls.": "使用 GLM 风格的带内工具调用。",
	Hermes: "Hermes",
	"Use Hermes-style in-band tool calls.": "使用 Hermes 风格的带内工具调用。",
	Kimi: "Kimi",
	"Use Kimi-style in-band tool calls.": "使用 Kimi 风格的带内工具调用。",
	XML: "XML",
	"Use generic XML in-band tool calls.": "使用通用 XML 带内工具调用。",
	Anthropic: "Anthropic",
	"Use Anthropic-style in-band tool calls.": "使用 Anthropic 风格的带内工具调用。",
	DeepSeek: "DeepSeek",
	"Use DeepSeek-style in-band tool calls.": "使用 DeepSeek 风格的带内工具调用。",
	Harmony: "Harmony",
	"Use Harmony-style in-band tool calls.": "使用 Harmony 风格的带内工具调用。",
	Qwen3: "Qwen3",
	"Use the Qwen3 owned dialect.": "使用 Qwen3 专属语法。",
	Gemini: "Gemini",
	"Use the Gemini owned dialect.": "使用 Gemini 专属语法。",
	Gemma: "Gemma",
	"Use the Gemma owned dialect.": "使用 Gemma 专属语法。",
	MiniMax: "MiniMax",
	"Use the MiniMax owned dialect.": "使用 MiniMax 专属语法。",
	"Picks a shape tuned for the current model, falling back to its provider family.":
		"选择针对当前模型优化的形状，无法匹配时回退到其提供商系列。",
	"8x8 repeated, black": "8x8 重复，黑色",
	"unscii square cell, black ink, every line printed twice with the copy on a pale highlight band.":
		"unscii 方形单元格，黑色字迹；每行打印两次，副本置于浅色高亮带上。",
	"8x8 repeated, sentence hues": "8x8 重复，句子色调",
	"Repeated grid with ink cycling six hues at sentence boundaries.": "重复网格，字迹在句子边界按六种色调循环。",
	"8x8, black": "8x8，黑色",
	"Plain unscii square cell, single-printed lines, black ink.": "普通 unscii 方形单元格，每行仅打印一次，黑色字迹。",
	"8x8, sentence hues": "8x8，句子色调",
	"Plain unscii square cell with sentence-hue ink.": "普通 unscii 方形单元格，使用句子色调字迹。",
	"6x6 dense, black": "6x6 高密度，黑色",
	"unscii squeezed to 6x6 — densest readable cell, fewest frames — in black ink.":
		"将 unscii 压缩至 6x6——可读单元格中密度最高、帧数最少——使用黑色字迹。",
	"6x6 dense, sentence hues": "6x6 高密度，句子色调",
	"Densest cell with sentence-hue ink.": "密度最高的单元格，使用句子色调字迹。",
	"5x8 legacy, black": "5x8 旧版，黑色",
	"Original X.org 5x8 glyphs on the 2576px frame, black ink.": "2576px 画幅上的原始 X.org 5x8 字形，黑色字迹。",
	"5x8 legacy, sentence hues": "5x8 旧版，句子色调",
	"The original snapcompact shape (pre-shape-table sessions rendered this).":
		"原始 snapcompact 形状（形状表推出前的会话使用此形状渲染）。",
	"6x12, dimmed stopwords": "6x12，弱化停用词",
	"X.org 6x12 glyphs, black ink, function words dimmed gray.": "X.org 6x12 字形，黑色字迹，功能词以较暗的灰色显示。",
	"8x13, black": "8x13，黑色",
	"X.org 8x13 glyphs, black ink.": "X.org 8x13 字形，黑色字迹。",
	"8x13 on 16px pitch, black": "8x13，16px 间距，黑色",
	"8x13 glyphs on an 8x16 cell (extra leading), black ink.": "8x16 单元格上的 8x13 字形（额外行距），黑色字迹。",
	"8x13 on 22px pitch (leading), black": "8x13，22px 间距（行距），黑色",
	"8x13 glyphs on an 8x22 cell — extra line spacing so rows don't crowd. Default for OpenAI/Google.":
		"8x22 单元格上的 8x13 字形——增加行距，避免各行拥挤。OpenAI/Google 的默认选项。",
	"8x13 on 11px advance (tracking), black": "8x13，11px 步进（字距），黑色",
	"8x13 glyphs on an 11x16 cell — extra letter spacing so characters don't merge. Default for Anthropic.":
		"11x16 单元格中的 8x13 字形——增加字母间距，避免字符粘连。Anthropic 的默认设置。",
	"Silver 16, CJK": "Silver 16，CJK",
	"Embedded Silver TrueType font on a 16px grid for CJK and other non-Latin text.":
		"在 16px 网格上嵌入 Silver TrueType 字体，用于 CJK 及其他非拉丁文字。",
	"Doc 8on16, black": "Doc 8on16，黑色",
	"Two word-wrapped newspaper columns of 8x13 glyphs on a 16px pitch, black ink.":
		"双栏报纸式自动换行布局，使用 16px 字距的 8x13 字形和黑色字迹。",
	"Doc 8on16, sentence hues": "Doc 8on16，句子色调",
	"Two-column doc layout with sentence-hue ink.": "双栏文档布局，字迹按句子着色。",
	"Doc 8on16, sentence hues + dimmed stopwords": "Doc 8on16，句子色调 + 淡化停用词",
	"Two-column doc layout, sentence-hue ink, function words dimmed gray.":
		"双栏文档布局，字迹按句子着色，功能词以淡灰色显示。",
	"No memory subsystem runs": "不运行记忆子系统",
	Local: "本地",
	"Local rollout summarisation pipeline (memory_summary.md)": "本地推演摘要管线（memory_summary.md）",
	Hindsight: "Hindsight",
	"Vectorize Hindsight remote memory service": "Vectorize Hindsight 远程记忆服务",
	Mnemopi: "Mnemopi",
	"Local SQLite recall/retain backend with optional embeddings": "本地 SQLite 回忆/保留后端，可选用嵌入",
	Sharpshooter: "Sharpshooter",
	"Friction-gated project decision files (architecture/product/style), consolidated in the background":
		"按摩擦信号沉淀项目决策文件（架构、产品、风格），并在后台合并",
	"One shared Mnemopi bank for every project": "所有项目共用一个 Mnemopi 记忆库",
	"Per project": "每个项目",
	"Project-local Mnemopi bank per cwd basename": "按 cwd 基名使用项目本地 Mnemopi 记忆库",
	"Per project (tagged)": "每个项目（带标签）",
	"Write to a project-local bank but merge project + shared recall results":
		"写入项目本地记忆库，但合并项目与共享回忆结果",
	"English (bge-base-en-v1.5)": "英语（bge-base-en-v1.5）",
	"BAAI/bge-base-en-v1.5 (768d), English-only": "BAAI/bge-base-en-v1.5（768d），仅英语",
	"Multilingual (multilingual-e5-large)": "多语言（multilingual-e5-large）",
	"intfloat/multilingual-e5-large (1024d), cross-language recall":
		"intfloat/multilingual-e5-large（1024d），跨语言回忆",
	"Disable Mnemopi LLM-backed extraction": "禁用由 LLM 支持的 Mnemopi 提取",
	"Online (tiny)": "在线（tiny）",
	"Use the online tiny model (the TINY role from /models, else @smol)":
		"使用在线 tiny 模型（优先使用 /models 中的 TINY 角色，否则使用 @smol）",
	Remote: "远程",
	"Use the Mnemopi remote LLM settings below": "使用下方的 Mnemopi 远程 LLM 设置",
	"One shared bank — every project sees the same memories": "一个共享记忆库——所有项目都能看到相同记忆",
	"Isolated bank per cwd basename — projects cannot see each other's memories":
		"按 cwd 基名使用隔离记忆库——项目之间无法看到彼此的记忆",
	"Shared bank, retains tagged with project:<cwd>. Recall surfaces project + untagged global memories together":
		"共享记忆库，保留内容标记为 project:<cwd>。回忆时同时显示项目记忆与无标签的全局记忆",
	"Full session": "完整会话",
	"Upsert one document per session (recommended)": "每个会话更新或插入一个文档（推荐）",
	"Last turn": "上一轮",
	"Chunked retention sliced by turn boundaries": "按轮次边界切分并分块保留",
	mid: "中途",
	discard: "丢弃",
	keep: "保留",
	"Interrupt on prose and tool streams": "在文本流和工具流中触发中断",
	"prose-only": "仅文本",
	"Interrupt only on reply/thinking matches": "仅在回复/思考匹配时中断",
	"tool-only": "仅工具",
	"Interrupt only on tool-call argument matches": "仅在工具调用参数匹配时中断",
	never: "从不",
	"Never interrupt; inject warning after completion": "从不中断；完成后插入警告",
	once: "一次",
	"after-gap": "间隔后",
	"5 messages": "5 条消息",
	"10 messages": "10 条消息",
	"15 messages": "15 条消息",
	"20 messages": "20 条消息",
	"30 messages": "30 条消息",
	apply_patch: "apply_patch",
	hashline: "hashline",
	patch: "patch",
	replace: "replace",
	Lenient: "宽松",
	Moderate: "适中",
	"200 lines": "200 行",
	"300 lines": "300 行",
	aggressive: "激进",
	session: "会话",
	"per-call": "每次调用",
	"Always ask": "始终询问",
	"Auto-approve read-only tools; require confirmation for write and exec tools.":
		"自动批准只读工具；写入和执行工具需要确认。",
	Write: "写入",
	"Auto-approve read-only and write tools; require confirmation for exec tools such as bash, eval, browser, and task.":
		"自动批准只读和写入工具；bash、eval、browser 和 task 等执行工具需要确认。",
	Yolo: "Yolo",
	"Auto-approve read, write, and exec tools. User policy can still require confirmation or block calls.":
		"自动批准读取、写入和执行工具。用户策略仍可要求确认或阻止调用。",
	"1 reminder": "1 次提醒",
	"2 reminders": "2 次提醒",
	"3 reminders": "3 次提醒",
	"5 reminders": "5 次提醒",
	"Model decides; no automatic todo list": "由模型决定；不自动创建待办清单",
	Preferred: "推荐",
	"Suggests a todo list on the first message (reminder, not forced)":
		"在第一条消息中建议创建待办清单（仅提醒，不强制）",
	Always: "始终",
	"Forces a comprehensive todo list on the first message": "在第一条消息中强制创建完整的待办清单",
	"0 lines": "0 行",
	"1 line": "1 行",
	"2 lines": "2 行",
	"3 lines": "3 行",
	"5 lines": "5 行",
	"10 lines": "10 行",
	"Auto (only for models without vision)": "自动（仅适用于无视觉能力的模型）",
	"3 minutes": "3 分钟",
	"No limit": "无限制",
	"5 seconds": "5 秒",
	"10 seconds": "10 秒",
	Smart: "智能",
	"Default — adaptive 5s→5m, resets when you stop polling": "默认——自适应 5 秒→5 分钟；停止轮询时重置",
	"All Devices": "所有设备",
	"Inline docs and schemas for every mounted device.": "内联显示每个已挂载设备的文档和架构。",
	"Built-ins Only": "仅内置项",
	"Inline built-in docs; fetch MCP and extension docs on demand.": "内联显示内置文档；按需获取 MCP 和扩展文档。",
	"Catalog Only": "仅目录",
	"List every device; fetch all docs on demand.": "列出所有设备；按需获取全部文档。",
	"No isolation": "不隔离",
	"Let the PAL pick the best available backend": "让 PAL 选择最佳可用后端",
	APFS: "APFS",
	"macOS clonefile reflink (APFS)": "macOS clonefile 引用链接（APFS）",
	btrfs: "btrfs",
	"btrfs subvolume snapshot": "btrfs 子卷快照",
	ZFS: "ZFS",
	"ZFS snapshot + clone": "ZFS 快照 + 克隆",
	Reflink: "引用链接",
	"Linux FICLONE per-file reflink": "Linux FICLONE 逐文件引用链接",
	Overlayfs: "Overlayfs",
	"Linux kernel overlay (or fuse-overlayfs fallback)": "Linux 内核叠加层（或回退到 fuse-overlayfs）",
	ProjFS: "ProjFS",
	"Windows Projected File System": "Windows 投影文件系统",
	"Block clone": "块克隆",
	"Windows FSCTL_DUPLICATE_EXTENTS_TO_FILE (NTFS/ReFS)": "Windows FSCTL_DUPLICATE_EXTENTS_TO_FILE（NTFS/ReFS）",
	"Recursive copy": "递归复制",
	"git worktree if available, otherwise recursive copy": "若可用则使用 git worktree，否则递归复制",
	Patch: "补丁",
	"Combine diffs and git apply": "合并差异并使用 git apply",
	Branch: "分支",
	"Commit per task, merge with --no-ff": "每个任务单独提交，使用 --no-ff 合并",
	Generic: "通用",
	"Static commit message": "固定提交消息",
	AI: "AI",
	"AI-generated commit message from diff": "由 AI 根据差异生成提交消息",
	"Model decides when to delegate": "由模型决定何时委派",
	"Adds delegation guidance to the system prompt": "在系统提示词中添加委派指导",
	"Prompt guidance plus a first-turn delegation reminder": "提示词指导，并在第一轮提醒委派",
	Unlimited: "无限制",
	"1 task": "1 个任务",
	"2 tasks": "2 个任务",
	"4 tasks": "4 个任务",
	"8 tasks": "8 个任务",
	"16 tasks": "16 个任务",
	"32 tasks": "32 个任务",
	"64 tasks": "64 个任务",
	Single: "单倍",
	Double: "双倍",
	Triple: "三倍",
	"15 minutes": "15 分钟",
	"90 requests": "90 次请求",
	"150 requests": "150 次请求",
	"200 requests": "200 次请求",
	Instant: "Instant",
	Perplexity: "Perplexity",
	"Uses auth when configured; explicit selection falls back to anonymous search":
		"配置后使用身份验证；显式选择时可回退到匿名搜索",
	"Google Search grounding via Gemini (uses google-gemini-cli or google-antigravity OAuth)":
		"通过 Gemini 使用 Google Search 进行依据检索（使用 google-gemini-cli 或 google-antigravity OAuth）",
	"Claude's native web_search tool (uses Anthropic OAuth or ANTHROPIC_API_KEY)":
		"Claude 原生 web_search 工具（使用 Anthropic OAuth 或 ANTHROPIC_API_KEY）",
	OpenAI: "OpenAI",
	"OpenAI's native web_search (uses ChatGPT OAuth via /login openai-codex)":
		"OpenAI 原生 web_search（通过 /login openai-codex 使用 ChatGPT OAuth）",
	xAI: "xAI",
	"Grok web search via xAI Responses API (uses SuperGrok/X Premium+ OAuth via /login xai-oauth, or XAI_API_KEY)":
		"通过 xAI Responses API 使用 Grok 网页搜索（通过 /login xai-oauth 使用 SuperGrok/X Premium+ OAuth，或使用 XAI_API_KEY）",
	"Z.AI": "Z.AI",
	"Calls Z.AI webSearchPrime MCP": "调用 Z.AI webSearchPrime MCP",
	Exa: "Exa",
	"API via /login exa or EXA_API_KEY; explicit keyless fallback via MCP":
		"通过 /login exa 或 EXA_API_KEY 使用 API；可显式通过 MCP 回退到无密钥模式",
	TinyFish: "TinyFish",
	"Requires TINYFISH_API_KEY": "需要 TINYFISH_API_KEY",
	Jina: "Jina",
	"Requires JINA_API_KEY": "需要 JINA_API_KEY",
	Kagi: "Kagi",
	"Requires KAGI_API_KEY and Kagi Search API beta access": "需要 KAGI_API_KEY 和 Kagi Search API Beta 访问权限",
	Tavily: "Tavily",
	"Requires TAVILY_API_KEY": "需要 TAVILY_API_KEY",
	Firecrawl: "Firecrawl",
	"Uses Firecrawl API when FIRECRAWL_API_KEY is set; falls back to keyless mode":
		"设置 FIRECRAWL_API_KEY 后使用 Firecrawl API；否则回退到无密钥模式",
	Brave: "Brave",
	"Requires BRAVE_API_KEY": "需要 BRAVE_API_KEY",
	"Kimi Code search (requires a Kimi Code Console key via KIMI_SEARCH_API_KEY/MOONSHOT_SEARCH_API_KEY or /login kimi-code; not MOONSHOT_API_KEY)":
		"Kimi Code 搜索（需要通过 KIMI_SEARCH_API_KEY/MOONSHOT_SEARCH_API_KEY 或 /login kimi-code 提供 Kimi Code Console 密钥；不是 MOONSHOT_API_KEY）",
	Parallel: "Parallel",
	"Requires PARALLEL_API_KEY": "需要 PARALLEL_API_KEY",
	Synthetic: "Synthetic",
	"Requires SYNTHETIC_API_KEY": "需要 SYNTHETIC_API_KEY",
	SearXNG: "SearXNG",
	"Requires SEARXNG_ENDPOINT or searxng.endpoint": "需要 SEARXNG_ENDPOINT 或 searxng.endpoint",
	Startpage: "Startpage",
	"Credential-free scrape of Startpage (Google-backed) results; may be bot-challenged":
		"无需凭据抓取 Startpage（由 Google 支持）的结果；可能遇到机器人验证",
	DuckDuckGo: "DuckDuckGo",
	"Credential-free best-effort fallback; may be bot-challenged on datacenter/shared-egress IPs":
		"无需凭据的尽力回退方案；使用数据中心/共享出口 IP 时可能遇到机器人验证",
	Ecosia: "Ecosia",
	"Credential-free browser-backed scrape of Ecosia (Google-backed) results":
		"无需凭据、通过浏览器抓取 Ecosia（由 Google 支持）的结果",
	Google: "Google",
	"Credential-free browser-backed fallback; slower and may be bot-challenged":
		"无需凭据、通过浏览器实现的回退方案；速度较慢，且可能遇到机器人验证",
	Mojeek: "Mojeek",
	"Credential-free browser-backed scrape of Mojeek's independent index": "无需凭据、通过浏览器抓取 Mojeek 的独立索引",
	"Public Web": "公共网络",
	"Queries every credential-free engine in parallel and consolidates deduplicated results":
		"并行查询所有无需凭据的引擎，并整合去重后的结果",
	"Try production endpoint, fail over to sandbox on 5xx/429": "先尝试生产端点，遇到 5xx/429 时故障转移到沙盒",
	"Production Only": "仅生产环境",
	"Force production endpoint only": "强制仅使用生产端点",
	"Sandbox Only": "仅沙盒环境",
	"Force sandbox endpoint only": "强制仅使用沙盒端点",
	"OPENAI_API_KEY (gpt-image-2) or active GPT model; falls back to a connected Codex subscription":
		"需要 OPENAI_API_KEY（gpt-image-2）或已启用的 GPT 模型；否则回退到已连接的 Codex 订阅",
	"OpenAI Codex (ChatGPT)": "OpenAI Codex（ChatGPT）",
	"Uses a connected Codex / ChatGPT subscription — no OPENAI_API_KEY needed":
		"使用已连接的 Codex / ChatGPT 订阅——无需 OPENAI_API_KEY",
	Antigravity: "Antigravity",
	"Requires google-antigravity OAuth": "需要 google-antigravity OAuth",
	"xAI Grok Imagine": "xAI Grok Imagine",
	"Requires xAI Grok OAuth or XAI_API_KEY": "需要 xAI Grok OAuth 或 XAI_API_KEY",
	"Requires GEMINI_API_KEY": "需要 GEMINI_API_KEY",
	OpenRouter: "OpenRouter",
	"Requires OPENROUTER_API_KEY": "需要 OPENROUTER_API_KEY",
	Standard: "标准",
	"Default serving path (no service_tier)": "默认服务路径（无 service_tier）",
	"Priority serving path: higher reliability, premium per-token pricing":
		"优先服务路径：可靠性更高，按 token 计费的价格更高",
	Arbor: "Arbor",
	Breeze: "Breeze",
	Cove: "Cove",
	Ember: "Ember",
	Juniper: "Juniper",
	Maple: "Maple",
	Sol: "Sol",
	Spruce: "Spruce",
	Vale: "Vale",
	"Prefer local on-device TTS; route .mp3 output to xAI when credentials exist":
		"优先使用本地设备端 TTS；存在凭据时，将 .mp3 输出交由 xAI 处理",
	"On-device neural TTS (Kokoro-82M); output is WAV/PCM16": "设备端神经网络 TTS（Kokoro-82M）；输出为 WAV/PCM16",
	"xAI Grok Voice": "xAI Grok Voice",
	"Requires xAI Grok OAuth or XAI_API_KEY; MP3 or WAV": "需要 xAI Grok OAuth 或 XAI_API_KEY；支持 MP3 或 WAV",
	"Kokoro-82M": "Kokoro-82M",
	"Kokoro-82M neural TTS — SoTA on-device quality, multi-voice, fully local":
		"Kokoro-82M 神经网络 TTS——设备端质量达到 SoTA，支持多种语音，完全本地运行",
	"Heart (American female)": "Heart（美国女声）",
	"Bella (American female)": "Bella（美国女声）",
	"Nicole (American female)": "Nicole（美国女声）",
	"Aoede (American female)": "Aoede（美国女声）",
	"Kore (American female)": "Kore（美国女声）",
	"Sarah (American female)": "Sarah（美国女声）",
	"Michael (American male)": "Michael（美国男声）",
	"Fenrir (American male)": "Fenrir（美国男声）",
	"Puck (American male)": "Puck（美国男声）",
	"Emma (British female)": "Emma（英国女声）",
	"George (British male)": "George（英国男声）",
	"Fable (British male)": "Fable（英国男声）",
	"All (messages + thinking)": "全部（消息 + 思考）",
	"Assistant messages": "助手消息",
	"Final message only": "仅最终消息",
	"Online (TINY role, else @smol)": "在线（TINY 角色，否则使用 @smol）",
	"Online title generation: the TINY model role (set one in /models) when assigned, otherwise the online fallback (commit role, then @smol). No local download or on-device inference.":
		"在线生成标题：已分配时使用 TINY 模型角色（在 /models 中设置），否则使用在线回退方案（先用 commit 角色，再用 @smol）。无需本地下载或设备端推理。",
	"LFM2 350M": "LFM2 350M",
	"Recommended local model; best speed/quality balance, about 212 MB cached.":
		"推荐的本地模型；速度与质量平衡最佳，缓存约 212 MB。",
	"Qwen3 0.6B": "Qwen3 0.6B",
	"Most robust local option; slower first load, about 500 MB cached.":
		"最稳健的本地选项；首次加载较慢，缓存约 500 MB。",
	"Gemma 270M": "Gemma 270M",
	"Smallest viable local option; lower quality, lowest cache footprint.":
		"可用的最小本地选项；质量较低，缓存占用最小。",
	"Qwen2.5 0.5B": "Qwen2.5 0.5B",
	"Balanced local fallback; moderate quality and cache footprint.": "均衡的本地回退方案；质量和缓存占用适中。",
	"LFM2 700M": "LFM2 700M",
	"Highest-quality local option; larger and slower than LFM2 350M.": "质量最高的本地选项；比 LFM2 350M 更大、更慢。",
	"CPU-only inference": "仅使用 CPU 推理",
	GPU: "GPU",
	"Accelerated provider (WebGPU/Metal, CUDA, or DirectML)": "加速提供程序（WebGPU/Metal、CUDA 或 DirectML）",
	CPU: "CPU",
	Metal: "Metal",
	"WebGPU alias for Apple GPUs": "Apple GPU 的 WebGPU 别名",
	WebGPU: "WebGPU",
	"WebGPU/Metal backend": "WebGPU/Metal 后端",
	CUDA: "CUDA",
	"NVIDIA CUDA (Linux x64)": "NVIDIA CUDA（Linux x64）",
	DirectML: "DirectML",
	"DirectML backend (Windows)": "DirectML 后端（Windows）",
	CoreML: "CoreML",
	"Apple CoreML (opt-in; can fail to load)": "Apple CoreML（选择启用；可能加载失败）",
	"Let ONNX Runtime choose a provider": "让 ONNX Runtime 选择提供程序",
	WASM: "WASM",
	"WebAssembly backend": "WebAssembly 后端",
	WebNN: "WebNN",
	"WebNN backend": "WebNN 后端",
	"WebNN GPU": "WebNN GPU",
	"WebNN GPU device": "WebNN GPU 设备",
	"WebNN CPU": "WebNN CPU",
	"WebNN CPU device": "WebNN CPU 设备",
	"WebNN NPU": "WebNN NPU",
	"WebNN NPU device": "WebNN NPU 设备",
	"Each model's shipped dtype (currently q4)": "每个模型随附的 dtype（目前为 q4）",
	q4: "q4",
	"4-bit weights; smallest and fastest": "4 位权重；体积最小、速度最快",
	q4f16: "q4f16",
	"4-bit weights with fp16 activations": "4 位权重，使用 fp16 激活值",
	q8: "q8",
	"8-bit quantization": "8 位量化",
	fp16: "fp16",
	"16-bit float; higher fidelity, larger": "16 位浮点数；保真度更高，体积更大",
	fp32: "fp32",
	"Full precision; largest and slowest": "全精度；体积最大、速度最慢",
	int8: "int8",
	"Signed 8-bit integer": "有符号 8 位整数",
	uint8: "uint8",
	"Unsigned 8-bit integer": "无符号 8 位整数",
	bnb4: "bnb4",
	"bitsandbytes 4-bit": "bitsandbytes 4 位",
	q2: "q2",
	"2-bit weights": "2 位权重",
	q2f16: "q2f16",
	"2-bit weights with fp16 activations": "2 位权重，使用 fp16 激活值",
	q1: "q1",
	"1-bit weights": "1 位权重",
	q1f16: "q1f16",
	"1-bit weights with fp16 activations": "1 位权重，使用 fp16 激活值",
	"Let transformers.js choose per device": "让 transformers.js 按设备选择",
	"Use the online model: the TINY role from /models when set, otherwise @smol. No local model download or on-device inference.":
		"使用在线模型：如已设置，则使用 /models 中的 TINY 角色，否则使用 @smol。无需下载本地模型或进行设备端推理。",
	"Qwen3 1.7B": "Qwen3 1.7B",
	"Disabled for local inference: onnxruntime-node cannot run this ONNX export's RotaryEmbedding cache updates.":
		"已禁用本地推理：onnxruntime-node 无法运行此 ONNX 导出中的 RotaryEmbedding 缓存更新。",
	"Llama 3.2 3B": "Llama 3.2 3B",
	"Larger Llama 3.2 option for local memory/classifier tasks; higher quality potential at higher disk/RAM/latency cost.":
		"用于本地记忆/分类器任务的较大 Llama 3.2 选项；质量潜力更高，但磁盘/RAM 占用和延迟也更高。",
	"Gemma 3 1B": "Gemma 3 1B",
	"Best consolidation/dedup; lighter footprint, but leaks small talk during extraction.":
		"整合/去重效果最佳；占用较小，但提取时会混入闲聊内容。",
	"Qwen2.5 1.5B": "Qwen2.5 1.5B",
	"Best extraction granularity (atomic facts); weaker consolidation.": "提取粒度最佳（原子事实）；整合能力较弱。",
	"LFM2 1.2B": "LFM2 1.2B",
	"Fastest load; solid all-rounder, slightly noisier extraction labels.":
		"加载最快；综合表现稳健，但提取标签略显杂乱。",
	"Classify prompt difficulty online with the TINY role model (set one in /models) or @smol; no local download or on-device inference.":
		"使用 TINY 角色模型（在 /models 中设置）或 @smol 在线评估提示词难度；无需本地下载或设备端推理。",
	"Classifier stops at xhigh (default)": "分类器最高评为 xhigh（默认）",
	"Classifier may resolve max where the model supports it": "模型支持时，分类器可评为 max",
	"Use the model's server-declared protocol": "使用模型服务器声明的协议",
	"api.kimi.com": "api.kimi.com",
	"api.moonshot.ai": "api.moonshot.ai",
	"Use model/provider default websocket behavior": "使用模型/提供商的默认 websocket 行为",
	"Disable websockets for OpenAI Codex models": "对 OpenAI Codex 模型禁用 websockets",
	"Force websockets for OpenAI Codex models": "对 OpenAI Codex 模型强制使用 websockets",
	"Use provider defaults and PI_* timeout env vars": "使用提供商默认值和 PI_* 超时环境变量",
	"Disable first-event timeout": "禁用首个事件超时",
	"Disable idle timeout": "禁用空闲超时",
	"No suffix; use OpenRouter's default routing": "无后缀；使用 OpenRouter 的默认路由",
	":nitro": ":nitro",
	"Prioritize throughput / lowest latency": "优先考虑吞吐量/最低延迟",
	":floor": ":floor",
	"Prioritize cheapest available provider": "优先选择价格最低的可用提供商",
	":online": ":online",
	"Enable OpenRouter's web-search plugin": "启用 OpenRouter 的网络搜索插件",
	":exacto": ":exacto",
	"Cherry-picked high-quality providers (only defined for select models)": "精选的高质量提供商（仅为部分模型定义）",
	"Priority: native > trafilatura > lynx > parallel > jina": "优先级：native > trafilatura > lynx > parallel > jina",
	"In-process HTML→Markdown converter (always available)": "进程内 HTML→Markdown 转换器（始终可用）",
	Trafilatura: "Trafilatura",
	"Auto-installs via uv/pip": "通过 uv/pip 自动安装",
	Lynx: "Lynx",
	"Requires lynx system package": "需要 lynx 系统软件包",
	"Uses r.jina.ai reader (JINA_API_KEY optional)": "使用 r.jina.ai 阅读器（JINA_API_KEY 可选）",
	Unset: "未设置",
	"Check eligibility, then ask before spending the first saved reset.":
		"检查资格，然后在使用第一个已保存的重置次数前询问。",
	Yes: "是",
	"Spend eligible saved resets without prompting.": "无需提示，直接使用符合条件的已保存重置次数。",
	No: "否",
	"Do not run the saved-reset auto-redeem check.": "不运行已保存重置次数的自动兑换检查。",
	"Enable for known prefix-cache providers (recommended)": "为已知支持前缀缓存的提供商启用（推荐）",
	"Always enable append-only context": "始终启用仅追加上下文",
	"Disable append-only context": "禁用仅追加上下文",
	unset: "未设置",
	granted: "已授权",
	denied: "已拒绝",
	// ── omp 18.2.x 新增枚举选项 ─────────────────────────────────────────────
	Braille: "布莱叶点",
	"Classic sweep (default)": "经典扫动（默认）",
	Pulse: "脉冲",
	"Moon filling cycle": "月相填充循环",
	Dots: "圆点",
	Line: "线条",
	Collapsed: "折叠",
	"Hide the pinned jump list": "隐藏固定跳转列表",
	"Show a few rows with an expander": "显示少量行并提供展开器",
	Percentage: "百分比",
	"Solid accent line, no context feedback": "实心强调线，不反馈上下文",
	"Used portion in accent color, remainder dimmed": "已用部分着强调色，其余变暗",
	Append: "追加",
	"Replay the transcript at the new width below retained history": "在保留历史下方按新宽度重放转录",
	Rebuild: "重建",
	"Erase all terminal scrollback, then replay one current-width transcript":
		"清空全部终端回滚区，再重放一份当前宽度的转录",
	View: "只读视图",
	"Share only when /collab is run": "仅在执行 /collab 时共享",
	"Auto-host; the registry hands out view-only links (omp collab link --view)":
		"自动托管；注册表分发只读链接（omp collab link --view）",
};
